### ISSUE TITLE
Characters inserted in any but the first buffer are displayed twice

### ISSUE THREAD

**Issue by martinwguy** [martinwguy/xvi#35]
Inserting a character in any but the first buffer of the screen displays the inserted character twice.

Repeat by:
echo foo > foo
echo bar > bar
xvi foo bar  #opens with cursor in second buffer, on the 'b'
ax

Result: instead of "bxar" it displays "bxxa".

This seems to happen in all open buffers except for the one at the top of the screen. If you open a third buffer and close the one at the top of the screen, whichever buffer endo up at the top of the screen now works OK, and the ones below it exhibit this symptom.  If the top two buffers are the result of a :split, inserting a space in one makes the top one display OK and the second one display the extra space.

**Comment by jvvv** [comment]
This issue is related to https://github.com/martinwguy/xvi/commit/1647a98b51be48d61662c251fd9cf60faef227b1. Reverting that commit fixes #35.

Making the call to xvUpdateAllBufferWindows() unconditionally in updateline() causes all windows to that buffer to get updated. This addresses #22.

I have https://github.com/jvvv/xvi/tree/issue35 that addresses both topics.
I am currently looking into optimising xvUpdateAllBufferWindows() before doing a pr.

**Comment by martinwguy** [comment]
Fixed by commit bf8cd78
